[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

# [program:mount-bwfs]
# command=/app/mount.bwfs -c /app/config.ini /app/mnt
# directory=/app
# autostart=true
# autorestart=true
# stderr_logfile=/var/log/supervisor/mount-bwfs.err.log
# stdout_logfile=/var/log/supervisor/mount-bwfs.out.log
# user=root

[program:bwfs-server]
command=/app/bwfs-server 8081
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/bwfs-server.err.log
stdout_logfile=/var/log/supervisor/bwfs-server.out.log
user=root
